name: "ssh on server"
on:
  workflow_dispatch:
jobs:
 TestSSH:
  runs-on: ubuntu-latest
  steps:
   - name: executing remote ssh commands using ssh key
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      script: |
        sed 's/dentacarts.com/DNS_NAME/' /var/www/html/config.local.php > output.php && sudo mv output.php /var/www/html/config.local.php
        sed 's/52.17.212.152/IP_Address/' /var/www/html/config.local.php > output.php && sudo mv output.php /var/www/html/config.local.php
        sed 's/auth.dentacarts.com/auth-staging.dentacartscloud.net/' /var/www/html/app/addons/dentacarts_auth/Tygh/HybridProvidersDCAuth.php > output.php && sudo mv output.php /var/www/html/app/addons/dentacarts_auth/Tygh/HybridProvidersDCAuth.php
