name: "Create Staging Environment"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-text: 'Hello World!'
        World: GitHub
    - run: echo ${{ steps.sub.outputs.result }} # Prints 'Hello GitHub!'
