name: "Replace String"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-file: '././config.local.php'
        dentacarts.com: Test.com
    - run: echo ${{ steps.sub.outputs.result }}
