name: "Replace String"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-file: '././config.local.php'
        dentacarts.com: Test.com
    - run: echo ${{ steps.sub.outputs.result }} # Prints 'Hello GitHub!'
